### ISSUE TITLE
--no-scale possibly not working for correlation and pcor

### ISSUE THREAD

**Issue by gianfilippo** [bschiffthaler/seidr#44]
Hi,

very nice package!

I am running a script like in your tutorial. My data are batch corrected and have negative values. Scales are very similar so I am running with the --no-scale flag.

correlation -t $dataDIR/$targetFILE -m pearson -i $dataDIR/$exprFILE -g $dataDIR/$geneFILE -o $outDIR/pearson_scores.tsv --no-scale

pcor -t $dataDIR/$targetFILE -i $dataDIR/$exprFILE -g $dataDIR/$geneFILE -o $outDIR/pcor_scores.tsv --no-scale

The output for both "correlation" and "pcor" still state "Transforming matrix to z-score", though, although it does not throw any error for the --no-scale flag.

Thanks

**Comment by bschiffthaler** [comment]
You're right, the flag that triggers scaling was invariably true (for all algorithms, including those that do not necessarily output a message - like `el-ensemble`, `genie3` etc.). I'm pushing a fix to the devel branch. If you build from source you can do that asap, otherwise I'm planning a version release via bioconda in January.

Thanks for noticing the issue!

**Comment by gianfilippo** [comment]
Thanks!
